# This is a basic workflow to help you get started with Actions

name: Test_CS

# Controls when the workflow will run
on:
  pull_request:
    branches:
    - master
    
 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    name: Unit Testing
    runs-on: windows-2019
    steps:
      - name: Unity - Test runner
        uses: game-ci/unity-test-runner@v2.0.0-alpha-7
        with:
          unityVersion: 2020.3.27f1
      - name: Unity - Builder
        uses: game-ci/unity-builder@v2.0.0-alpha-14
        with:
          targetPlatform: StandaloneWindows
          unityVersion: 2020.3.27f1
