# This is a basic workflow to help you get started with Actions

name: Test_CS

# Controls when the workflow will run
on:
  pull_request:
    branches:
    - master
    
 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    name: Unit Testing
    runs-on: windows-latest
    steps:
      - uses: game-ci/unity-test-runner@v2.0.0-alpha-7
        with:
          unityVersion: 2020.3.27f1
