# This is a basic workflow to help you get started with Actions

name: Test_CS

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

# Controls when the workflow will run
on:
  pull_request:
    branches:
    - master
    
 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  testAllModes:
    name: Test in ${{ matrix.testMode }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest 
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - ./
        unityVersion:
          - 2020.3.27f1
        testMode:
          - playmode
          - editmode
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: false # will be true eventually
          
      - name: Tests
        uses: game-ci/unity-test-runner@v2
        with:
          projectPath: ${{ matrix.projectPath }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          unityVersion: ${{ matrix.unityVersion }}
          testMode: ${{ matrix.testMode }}
          checkName: ${{ matrix.testMode }} Test Results
          customParameters: '-nographics'
